### ISSUE TITLE
Constructor fails inside an array under xUnit

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [fsprojects/FSharp.ViewModule#10]
```
type AccidentDataModel (accidentId,displayText,code) as self =
    inherit FSharp.ViewModule.ViewModelBase()

    let accidentId      = self.Factory.Backing  (<@ self.AccidentID @>,         accidentId)
    let displayText     = self.Factory.Backing  (<@ self.DisplayText @>,        displayText)
    let code            = self.Factory.Backing  (<@ self.Code @>,               code)

    new () = AccidentDataModel(0,String.Empty,String.Empty)

    member x.AccidentID with get() = accidentId.Value and set v = accidentId.Value <- v
    member x.DisplayText with get() = displayText.Value and set v = displayText.Value <- v
    member x.Code with get() = code.Value and set v = code.Value <- v
```

Succeeding test

```
open global.Xunit
open FsCheck
open FsCheck.Xunit
            [<Property>]
            let createAccidentModelTest x y z = 
                let model = Pm.Dal.DataModels.AccidentDataModel(x,y,z)
                Assert.NotNull model 
                Assert.Equal(x,model.AccidentID)
                Assert.Equal(y, model.DisplayText)
                Assert.Equal(z, model.Code)
```

Failing test for both cases 1, and 100

```
            [<Theory>]
            [<InlineData(1)>]
            [<InlineData(100)>]
            let createAccidentList length = 
                //generate a single instance of 't
                let generateOne() = FsCheck.Arb.generate<'a>.Sample(1,1) |> Seq.head
                let generateAdm () = Pm.Dal.DataModels.AccidentDataModel(generateOne() , generateOne(), generateOne())
                let items = 
                    [0..length-1]
                    |> Seq.map (ignore >> generateAdm)
                    |> Array.ofSeq
                Assert.NotNull items
                Assert.Equal(items.Length,length)
```

exception 

> 
> Test Name:	Pm.Tests.IntegrationTests.IntegrationTestModule+DataAccess+Accidents.createAccidentList(length: 100)
> Test FullName:	Pm.Tests.IntegrationTests.IntegrationTestModule+DataAccess+Accidents.createAccidentList
> Test Source:	C:\TFS\PracticeManagement\dev\PracticeManagement\Pm.Tests\Integration.XUnit.fs : line 263
> Test Outcome:	Failed
> Test Duration:	0:00:00.229
> 
> Result StackTrace:	
> at Microsoft.FSharp.Core.LanguagePrimitives.IntrinsicFunctions.FailInit()
>    at FSharp.ViewModule.Internal.ViewModelUntyped.Validate(String propertyName)
>    at FSharp.ViewModule.ValidationTracker.validatePropertiesInternal(String propertyName)
> Result Message:	System.InvalidOperationException : The initialization of an object or value resulted in an object or value being accessed recursively before it was fully initialized.
> 
>

**Comment by ReedCopsey** [comment]
@ImaginaryDevelopment Would it be possible to make a standalone reproducible example of this?  Ideally, something that reproduces in FSI or simliar?

I'm not sure what's happening, but it'd be nice to narrow down what causes this to go crazy, since it's not obvious from your code above.

**Comment by ImaginaryDevelopment** [comment]
stand-alone repro solution
[FsXamlXUnit.bug.zip](https://github.com/fsprojects/FSharp.ViewModule/files/123132/FsXamlXUnit.bug.zip)

**Comment by ImaginaryDevelopment** [comment]
any news on this?

**Comment by ReedCopsey** [comment]
So, finally managed to track this down.

@ImaginaryDevelopment It turns out the problem is that xUnit is setting up a synchronization context that's wholly inappropriate for UI work in this case.

You can work around it by removing the context in your test:

```fsharp
[<Theory>]
[<InlineData(1)>]
[<InlineData(100)>]
let createAccidentList length = 
    System.Threading.SynchronizationContext.SetSynchronizationContext(null)
    let generateAdm () = AccidentDataModel(generateOne() , generateOne(), generateOne())
    let items = 
        [0..length-1]
        |> Seq.map (fun _ -> generateAdm())
        |> Array.ofSeq
    Assert.NotNull items
    Assert.Equal(items.Length,length)
```

If you remove this, then it works perfectly.

**Comment by amazingant** [comment]
Just spent about an hour trying to figure out the same `InvalidOperationException` result in a unit test before seeing this; I got as far as changing [this line](https://github.com/fsprojects/FSharp.ViewModule/blob/aa52b922db97e7b6f292fa758c2a4a1b5be93e5a/src/FSharp.ViewModule/MVVM.fs#L160) to:

```FSharp
let errorTracker = ValidationTracker(self.RaiseErrorChanged, propertyChanged.Publish, (fun (_) -> Seq.empty), errorRelatedProperties)
```

and this also clears up the error. Is there some other "proper" way that the `ViewModelUntyped` ctor should be referencing the abstract member `Validate` that wouldn't cause this? Or should I just be cleaning up the `SynchronizationContext` as well?
