### ISSUE TITLE
Unable to load the FSharp.ViewModule project in Visual Studio 2015 update 1

### ISSUE THREAD

**Issue by ScottHutchinson** [fsprojects/FSharp.ViewModule#13]
The FSharp.ViewModule project fsproj file fails to load with an error at Line 62:

<Import Project="$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.1\Framework\v4.0\Microsoft.Portable.FSharp.Targets" />

Error		The imported project "C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\Microsoft.Portable.FSharp.Targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.	FSharp.ViewModule.Wpf	C:\...\FSharp.ViewModule-master\src\FSharp.ViewModule\FSharp.ViewModule.fsproj	62	

After commenting out this line, I was still unable to get the project to load.

**Comment by ReedCopsey** [comment]
I believe you need to install 3.1 as well, from https://www.microsoft.com/en-us/download/details.aspx?id=44011

**Comment by ScottHutchinson** [comment]
Yes, that did the trick. After installing that, it loads and builds perfectly. Thank you for your prompt response. Perhaps, you could add that requirement to the readme.md file.



------ Original Message ------
   Received: 08:59 AM PST, 03/02/2016

**Comment by ReedCopsey** [comment]
@ScottHutchinson Any chance you feel like doing a PR? ;)

**Comment by ScottHutchinson** [comment]
I'd like to do that, but sorry I'm a complete newbie on GitHub. I just completed the tutorial, but when I try to create a new branch on this project nothing happens, so I'm not sure how to proceed.
