### ISSUE TITLE
TypeProvider removed with no migration plan or forwarding address

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [fsprojects/FSharp.ViewModule#15]
so for those of us relying on the type provider, what is the proposed plan? It took me awhile to figure out that the simple version update was a major breaking change, in assembly name, and in what's inside the dll.

**Comment by ReedCopsey** [comment]
I'd be curious what you're doing with it - It was always "experimental" at best, and never found anybody who wanted to use it beyond playing around, as it's so brittle and difficult to manage.

I think it could be put into its own project fairly easily, though, depending on what functionality you were using.

**Comment by ImaginaryDevelopment** [comment]
turns out it wasn't the type provider, it was `NotifyingValue` -> `INotifyingValue` 
sample before and after:
```
    let selectedAppointment:NotifyingValue<'tAppt option> = self.Factory.Backing(<@ self.SelectedAppointment @>,None)

```

became 
```
    let selectedAppointment:INotifyingValue<'tAppt option> = self.Factory.Backing(<@ self.SelectedAppointment @>,None)
```

**Comment by ReedCopsey** [comment]
BTW - you shouldn't need to put the type on this at all - which is why I didn't worry about this.  Worst case, you could decorate the default value instead:

```fsharp
let selectedAppointment = self.Factory.Backing(<@ self.SelectedAppointment @>,None : 'tAppt option)
```

However, the member type should have enough information to make the type checker happy without that.
