### ISSUE TITLE
CommandAsyncChecked does not respect CanExecute's return value

### ISSUE THREAD

**Issue by WallaceKelly** [fsprojects/FSharp.ViewModule#16]
### Description

When I create a WPF Command with `Factory.CommandAsyncChecked(asyncWorkflow, canExecute)`, and bind that command to a button, and click the button, the button becomes disabled and does not become re-enabled. It does this even if `canExecute` always returns true.

### Repro steps

1. Create a new F# project
1. Reference FSharp.ViewModule.Core, 0.9.9.2 and FsXaml.Wpf, 0.9.9.
1. Use the code below.
1. Run the program. Press the button.
1. Observe that the button becomes disabled and never re-enabled.

MainWindow.xaml

    <Window xmlns="http://schemas.microsoft.com/netfx/2009/xaml/presentation"
            xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
        <Button Width="200" Height="100"
                Command="{Binding DoSomethingAsync}"
                Content="DoSomethingAsync" />
    </Window>

Program.cs

    open System
    open System.Windows
    open FSharp.ViewModule

    type MainWindow = FsXaml.XAML< "MainWindow.xaml", true >

    type MainWindowViewModel() as this = 
        inherit ViewModelBase()
        let asyncWorkflow _ =
            async {
                do! Async.Sleep(3000)
                System.Diagnostics.Debug.WriteLine("asyncWorkflow completed.")
            }
        let canExecute _ = true
        member val DoSomethingAsync =
            this.Factory.CommandAsyncChecked(asyncWorkflow, canExecute)

    [<STAThread; EntryPoint>]
    let main argv = 
        let win = MainWindow()
        win.Root.DataContext <- MainWindowViewModel()
        let app = Application()
        app.Run(win.Root)

### Expected behavior

I expected that the button would never become disabled.

### Actual behavior

The button becomes disabled and does not become re-enabled. 

### Known workarounds

I found that the button can become re-enabled with this code:

    type MainWindowViewModel() as this = 
        inherit ViewModelBase()
        let asyncWorkflow _ =
            async {
                try
                    this.OperationExecuting <- true
                    do! Async.Sleep(3000)
                    System.Diagnostics.Debug.WriteLine("asyncWorkflow completed.")
                finally
                    this.OperationExecuting <- false
            }
        let canExecute _ = true
        member val DoSomethingAsync =
            this.Factory.CommandAsyncChecked(asyncWorkflow, canExecute, [ <@ this.OperationExecuting @> ])

I'm not sure if that is the intended use of `OperationExecuting`. It seems that the library could set and unset `OperationExecuting`, but it apparently does not. 

Regardless, `canExecute` always returns true, so I expected the command never to become disabled. 

### Related information 

* Windows 10
* Visual Studio 2015
* .NET Framework 4.5.2, FSharp.Core 4.4.0.0

**Comment by FoggyFinder** [comment]
A similar question has already been asked on SO:

http://stackoverflow.com/questions/35554054/f-wpf-async-command-completion-status/35558857

Thus:

```
    [<STAThread; EntryPoint>]
    let main argv = 
        if SynchronizationContext.Current = null then
            DispatcherSynchronizationContext(Dispatcher.CurrentDispatcher)
            |> SynchronizationContext.SetSynchronizationContext
        let win = MainWindow()
        win.Root.DataContext <- MainWindowViewModel()
        let app = Application()
        app.Run(win.Root)
```

**Comment by WallaceKelly** [comment]
@FoggyFinder Thank you for the SO link. I had not found that. 

I added the code to SetSynchronizationContext to my demo. It is an improvement. The button becomes re-enabled when the asyncWorkflow completes. However, I want to do some more research. The behavior is still not exactly what I would have expected. (I would not have expected the button to be disabled while the asyncWorkflow runs.) But, my expectations may be the problem. Thanks again!

**Comment by ReedCopsey** [comment]
@WallaceKelly we don't always disable, because there are times when people want to allow more than one execution. 

If you make can execute return `not self.OperationExecuting` it'll disable and re-enable automatically

**Comment by WallaceKelly** [comment]
@ReedCopsey I'm glad to hear how you describe it, because that is what I expected. However, that is not what I'm seeing. The behavior I'm seeing is that the button becomes disabled, only allowing one execution, even if my canExecute always returns true.

**Comment by ReedCopsey** [comment]
@WallaceKelly I'm not sure I follow - you definitely need @FoggyFinder 's workaround (the Sync Context setup I posted in SO).  That's actually an issue in C# if you build your own app, too, and use async/await heavily in the VM. 

Once that's there, if you change your CanExecute as I mentioned, it should enable/disable:

```fsharp
let canExecute _ = not self.OperationExecuting
member val DoSomethingAsync =
        this.Factory.CommandAsyncChecked(asyncWorkflow, canExecute, [ <@ this.OperationExecuting @> ])
```

This sample from FsXaml shows some ideas around using operation executing: https://github.com/fsprojects/FsXaml/blob/master/demos/WpfMvvmAgent/MainViewModel.fs

If it's still not working, can you post a full repro? I'll take a look.

**Comment by FoggyFinder** [comment]
> (I would not have expected the button to be disabled while the asyncWorkflow runs.) 

@WallaceKelly, You mean something like this?

```
    let asyncWorkflowS() =
        async {
            do! Async.Sleep(3000)
            System.Diagnostics.Debug.WriteLine("asyncWorkflow completed.")
        } |> Async.Start

    member val DoSomethingAsync =
        this.Factory.CommandSyncChecked(asyncWorkflowS, canExecute)
```
