### ISSUE TITLE
Where is this.Factory.SetPropertyDependencies?

### ISSUE THREAD

**Issue by lijunle** [fsprojects/FSharp.ViewModule#19]
### Description

I am learning to use FSharp.ViewModule package from the Youtube video: https://www.youtube.com/watch?v=z6R85_X2ivE

At the screenshot of 16:16, you are using `self.Factory.SetPropertyDependencies()` to manage the case a property depends on two fileds.

However, I don't find such API from this package. Do I miss somthing?

### Related information 

* Operating system: Windows 10
* Branch: From NuGet

**Comment by FoggyFinder** [comment]
This is a pretty old video. I think this functionality is now available through the type `IDependencyTracker`.
So, use:

`self.DependencyTracker.AddPropertyDependencies:`

> AddPropertyDependencies : Expr * Expr list -> unit  
> AddPropertyDependencies : string * string list -> unit

**Comment by lijunle** [comment]
Awesome! It is working! @FoggyFinder Thank you very much!
