### ISSUE TITLE
RaiseCanExecuteChanged does not fire?

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/FSharp.ViewModule#26]
### Description

I have two commands. When the first command executes, I want it to explicitly force the second command's CanExecuteChanged to be re-checked by WPF. Inside the first command, I call ``RaiseCanExecuteChanged()`` on the second command, but the second command's CanExecuteChanged predicate does not get called.

What am I doing wrong?

**Comment by FoggyFinder** [comment]
@isaacabraham Can you provide MCVE?

**Comment by isaacabraham** [comment]
At the moment, no - at this point, before I do that, I'm just trying to understand if what I'm doing is correct i.e. should calling ``RaiseCanExecuteChange()`` on a command force WPF to call ``CanExecuteChanged`` on the command?

**Comment by giuliohome** [comment]
Maybe it's just a typo, but in the first command (the one that executes) you raise the Changed of the second (the one that you want to force recheck). It looks like you wrote the opposite : -)

**Comment by isaacabraham** [comment]
@giuliohome good spot - fixed :-)

**Comment by FoggyFinder** [comment]
I just can't understand the problem, maybe you want to use dependencies?

**Comment by isaacabraham** [comment]
@FoggyFinder that's what I was using originally but due to the way that the view model is now working, it's not possible any more - hence why I'm now explicitly trying to force the second command to refresh it's can execute state.

**Comment by ReedCopsey** [comment]
Does the command have a parameter?  You'll get a silent fail if the
parameter can't be coerced to the right type.

That being said, I'd highly recommend using a dependency.  The method
you're calling can always set a dependency to the right value, which in
turn will handle the command...

**Comment by ReedCopsey** [comment]
@isaacabraham Any update on this?  Want to figure out whether it's a problem in the library, or something else...

**Comment by isaacabraham** [comment]
My bad. I have a bit of time tomorrow and I'll try to repro it, or close if I can't.

**Comment by ReedCopsey** [comment]
@isaacabraham Thanks - Just don't want to leave you in the dark if it's something I can fix

**Comment by isaacabraham** [comment]
Here's a simple repro: -

https://github.com/isaacabraham/viewmodel-command

**Comment by ReedCopsey** [comment]
@isaacabraham The problem is that you weren't actually ever calling `RaiseCanExecuteChanged` on the _instance bound in the view_.  Since you were creating the command directly in the property get code, a new instance is constructed each time you call `vm.DependentCommand` - that new instance becomes enabled, but the view still was holding onto the original instance.

I've put in a PR against your repo to illustrate how to fix, with comments.

**Comment by isaacabraham** [comment]
Thanks for this @ReedCopsey - much appreciated!
