### ISSUE TITLE
Execption raises when asynchronous call to a dependent propertie

### ISSUE THREAD

**Issue by Ummon** [fsprojects/FSharp.ViewModule#29]
### Description

In my view model I have a dependent property like that with a associated command:

~~~ f#
type MyViewModel () as this =
    inherit ViewModelBase ()
    let saveCurrent () = ...
    let dirty = this.Factory.Backing(<@ this.Dirty @>, false)
    let saveCommand =
        this.Factory.CommandSyncChecked(
            saveCurrent,
            (fun () -> this.Dirty),
            [ <@ this.Dirty @> ]
        )
    // ...
    member private this.Dirty
        with get () = dirty.Value
        and set value = dirty.Value <- value
    member this.SaveCommand = saveCommand
~~~

If this.Dirty is modified from another thread than the UI thread then an exception is raised : 

~~~
Unhandled error in web service loop: System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   at System.Windows.Controls.Primitives.ButtonBase.get_Command()
   at System.Windows.Controls.Primitives.ButtonBase.UpdateCanExecute()
   at <StartupCode$FSharp-ViewModule>.$DefaultImplementations.clo@180-3.Invoke(INotifyCommand cmd, Unit unitVar0)
   at Microsoft.FSharp.Primitives.Basics.List.iter[T](FSharpFunc`2 f, FSharpList`1 x)
   at ViewModule.DependencyTracker.handleTrackingActions(PropertyChangedEventArgs args)
   at <StartupCode$FSharp-ViewModule>.$DefaultImplementations.-ctor@213-3.Invoke(PropertyChangedEventArgs args)
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at <StartupCode$FSharp-ViewModule>.$MVVM.propChanged@57.Invoke(String arg00)
   at MyViewModel.FileDetailsPartViewModel.SetCurrentFileIds(FSharpList`1 ids) in Part\FileDetailsPartView.fs:line 102
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.Observer`1.OnNext(T value)
   ...
~~~

### Repro steps

Call `this.Dirty` from the sample above from another thread than the UI thread. For example the exception stack trace shows a call from an IObservable.

### Expected behavior

ViewModel should be independent from the UI thread and therefore not crash should happen.

### Actual behavior

It crashes.

### Known workarounds

With a dirty code like that it doesn't crash : 

~~~ f#
    member private this.Dirty
        with get () = dirty.Value
        and set value =
            Application.Current.Dispatcher.Invoke(
                fun () -> dirty.Value <- value
            )
~~~

### Related information 

* Operating system: Window 7
* .NET Runtime: 4.6.1 (F# 4.0)
* FSharp.ViewModule.Core version (from NuGet): v1.0.5

**Comment by ReedCopsey** [comment]
WPF is very "fussy" about threading issues.  Simple properties can be set from other threads, but anything that touches the UI in more convoluted ways (commands, collections, etc) must always be set, or at least notified, from the UI thread.

In this case, it's the Command's CanExecuteChanged event - that needs to happen on the UI thread.

We don't track the current context within every command - it adds quite a bit of overhead.  However, the dependency notification system does provide a mechanism to allow this.  Unfortunately, it got hidden in the major API update recently.

I've just pushed Version 1.0.6 to NuGet ( https://www.nuget.org/packages/FSharp.ViewModule.Core/1.0.6 ), which re-exposes this.

With this release, you can now make any ViewModel become "thread aware" on an opt-in basis by adding a single line of code. Just change your definition to:

```fsharp
type MyViewModel () as this =
    inherit ViewModelBase ()
    do
        this.DependencyTracker.SynchronizationContext <- System.Threading.SynchronizationContext.Current

    // ... rest of your code here
```

This causes all dependent property notifications to post to the UI thread, which should solve your issue.

**Comment by ReedCopsey** [comment]
Going to close this - feel free to reopen if you're still having issues, or ask if you need more clarification.

**Comment by Ummon** [comment]
Thanks for your answer. It solves my problem.
